### ISSUE TITLE
申请加入应用AdGuard Home Manager

### ISSUE THREAD

**Issue by TearGlass** [misaka-13766/Material-You-App-Repository#1]
https://github.com/JGeek00/adguard-home-manager
应用为AdGuard Home的软件管理器，其也内置了网页管理器的快捷方式，但功能更为直观、多样
tips：无中文

**Comment by misaka-13766** [comment]
这个之前有记录的，在“开发工具-服务器”那一栏。

另外，感谢提出补充建议www
