### ISSUE TITLE
New Apps

### ISSUE THREAD

**Issue by TearGlass** [misaka-13766/Material-You-App-Repository#10]
名称：MaterialGPT
类别：小工具/AI
项目地址：https://github.com/DylanAkp/MaterialGPT

截图
![Screenshot_2023-07-05-19-48-31-488_dev.dylanakp.materialgpt.jpg](https://github.com/misaka-13766/Material-You-App-Repository/assets/93420845/1a7538b6-f360-4c31-8287-20f443eb3067)

（因为没有openAI key所以聊天演示不了😶‍🌫️）

**Comment by misaka-13766** [comment]
@TearGlass 草，你直接搁电报群里发就好了 (
