### ISSUE TITLE
请求添加一款应用

### ISSUE THREAD

**Issue by qgmzmy** [misaka-13766/Material-You-App-Repository#5]
## 希望可以添加一款名为Batt的应用
- Batt 是一个简单的应用程序，可以在 Android 设备上显示电池状态信息。
- Batt 可能需要 <a href="https://developer.android.google.cn/about/versions/14" title="Android 14  |  Android 开发者  |  Android Developers">Android 14</a> 及以上的 Android 版本，以及 [Shizuku](https://shizuku.rikka.app/ "Shizuku")。
---
项目地址：[https://gitlab.com/narektor/batt](https://gitlab.com/narektor/batt "Narek / Batt · GitLab")
Markdown：```- [Batt](https://gitlab.com/narektor/batt) **`MD-` `FOSS`**```
---
[![screenshot.png](https://gitlab.com/narektor/batt/-/raw/main/screenshot.png "screenshot.png")](https://gitlab.com/narektor/batt/-/raw/main/screenshot.png)
[README_zh-CN.md](https://github.com/misaka-13766/Material-You-App-Repository/files/11644474/README_zh-CN.md)
[README.md](https://github.com/misaka-13766/Material-You-App-Repository/files/11644475/README.md)

**Comment by misaka-13766** [comment]
@qgmzmy 我囸

**Comment by qgmzmy** [comment]
emm

**Comment by qgmzmy** [comment]
> @qgmzmy 我囸

emm

**Comment by misaka-13766** [comment]
> emm

就很尴尬，我刚才在电报群跟人聊天，不小心ping错消息了，我也不知道回复github机器人会直接把reply发送出去，特别抱歉......

**Comment by misaka-13766** [comment]
@qgmzmy 我这边暂时测试不了这个应用，因为暂时没有A14的设备，能麻烦再提供几张截图嘛？

**Comment by qgmzmy** [comment]
> @qgmzmy 我这边暂时测试不了这个应用，因为暂时没有A14的设备，能麻烦再提供几张截图嘛？

在我的Pixel5中似乎遇到了一点问题![Screenshot_20230604-080521.png](https://github.com/misaka-13766/Material-You-App-Repository/assets/114319143/24c1f221-e5c0-4fa6-93a7-6eba05a3eb6a)

您可以在 [来自 酷腾哈 - 酷安](https://www.coolapk.com/feed/46534935?shareKey=NjU2YjAxZmVjODQyNjQ3YmQ1NTM~&shareUid=22766096&shareFrom=com.coolapk.market_13.1.5 "来自 酷腾哈 - 酷安") 中查看来自其他人的截图

**Comment by misaka-13766** [comment]
@qgmzmy OK，酷腾哈也是 (酷安MIUI板块) 的熟人了，我瞅瞅XD

**Comment by misaka-13766** [comment]
添加进去力！

**Comment by qgmzmy** [comment]
> 添加进去力！

GayHub果然不是随便叫的😂

**Comment by misaka-13766** [comment]
> > 添加进去力！
> 
> GayHub果然不是随便叫的😂

(警撅)
