### ISSUE TITLE
又来提交应用啦

### ISSUE THREAD

**Issue by qgmzmy** [misaka-13766/Material-You-App-Repository#6]
> 包含部分PC应用
---
1. 附近分享 Beta  
Google 附近分享 的 Windows 版，我平时在手机和电脑之间传输文件就靠它！☺️  
[Nearby Share Beta for Windows](https://android.com/better-together/nearby-share-app/) **`MD`**
  
Markdown：```- [Nearby Share Beta for Windows](https://android.com/better-together/nearby-share-app/) **`MD`**```  

2. 云端硬盘
云端硬盘的 Windows 和 Mac 版。  
[Google Drive](https://support.google.com/a/users/answer/13022292#drive_desktop_install) **`MD`**

Markdown：```- [Google Drive](https://support.google.com/a/users/answer/1302229#drive_desktop_install) **`MD`**```

3. Markdown Editor
一款支持 Material You 的 Markdown 编辑器。  
[Markdown Editor](https://play.google.com/store/apps/details?id=com.adeeteya.markdown_editor) **`MD`**

Markdown：```- [Markdown Editor](https://play.google.com/store/apps/details?id=com.adeeteya.markdown_editor) **`MD`**```
> 有点小缺点，这款编辑器不支持渲染 HTML 标签，并且深色模式下渲染结果可能会不易查看

4. VPN 热点
通过无线中继或系统共享共享你的 VPN。(须要 root).  
[VPN Hotspot](https://github.com/Mygod/VPNHotspot) **`MD` `FOSS`**   
或  
[VPN Hotspot](https://play.google.com/store/apps/details?id=be.mygod.vpnhotspot) **`MD` `FOSS`**

Markdown：```- [VPN Hotspot](https://github.com/Mygod/VPNHotspot) **`MD` `FOSS`**``` or ```- [VPN Hotspot](https://play.google.com/store/apps/details?id=be.mygod.vpnhotspot) **`MD` `FOSS`**```

5. 无障碍管理器  
[无障碍管理器](https://www.coolapk.com/apk/com.accessibilitymanager) **`MD-`**

Markdown：```- [无障碍管理器](https://www.coolapk.com/apk/com.accessibilitymanager) **`MD-`**```

6. 快捷方式  
[快捷方式](https://www.coolapk.com/apk/com.syyf.quickpay) **`Full`**

Markdown：```- [快捷方式](https://www.coolapk.com/apk/com.syyf.quickpay) **`Full`**```

**Comment by qgmzmy** [comment]
> @qgmzmy 4，6已经在列表中了，再好好查看下列表发现它们吧XD (也可能是我分类做的太乱导致您没发现，之后我会调整下分类索引)。
> 
> 1，2不考虑添加，本列表只收录基于Material You (D3) 设计的移动端应用，因为个人觉得Material You在电脑端、iOS端等处的使用是坏文明。有一个名为Music You的应用，您可以在github中找到，在今年年初我就已经开始用了，这是一款基于Material You设计的PC应用，但是我并没有将其纳入列表中。
> 
> 3，5 sound good ideas，我稍后会加进去。
> 
> 非常感谢您的issue，太辛苦您了XD，给大佬倒一杯卡布奇诺.jpg

我在浏览器中ctrl+f搜索没搜到就写进去了😂

**Comment by misaka-13766** [comment]
@qgmzmy 。。。VPN热点我好像还真没写，怎么会是呢；快捷方式列表中写的是英文 (shortcuts) ，这个倒是可以找到

**Comment by misaka-13766** [comment]
@qgmzmy 总之特别感谢(◦˙▽˙◦)
