### ISSUE TITLE
✨ Requests ✨

### ISSUE THREAD

**Issue by TeaEndsAcronyms** [misaka-13766/Material-You-App-Repository#9]
1. The Table of content (📜Applist Menu)  needs~... some work ._. You could use DocToc, or Smart TOC to make a better applist :)
2. Add [Nothing weather (not the modded one)](https://www.apkmirror.com/apk/nothing-technology-limited/nothing-weather/), Its `MD`. (correct me if im wrong, lol)
3. [Signal](https://github.com/signalapp/Signal-Android), Which is `MD` + `FOSS`
4. Recently [Arcticons You](https://github.com/Donnnno/Arcticons) was made, which is `MDY` + `FOSS`!
5. There is a [fork of jetispot](https://github.com/BobbyESP/Jetispot)
6. Question: I cant seem to use (most) CoolAPK links, i would assume this would be a problem with my location? if so, would a VPN work? also, are there any security risks with apps uploaded in coolAPK?

### Thats it, and thanks for the great list! :)

**Comment by misaka-13766** [comment]
@TeaEndsAcronyms Thanks for your issue! I'll accept the first to fifth recommendations. 

And for the sixth, as Coolapk bans seriously for non-China regions, you should access these links by VPN lol.

As for security risks, you ahould never mind as these softwares are uploaded by the developers themselves and Coolapk is one standard way to download apps in China.

Thanks again for your issue:)

**Comment by TeaEndsAcronyms** [comment]
> @TeaEndsAcronyms Thanks for your issue! I'll accept the first to fifth recommendations. 
> 
> And for the sixth, as Coolapk bans seriously for non-China regions, you should access these links by VPN lol.
> 
> As for security risks, you ahould never mind as these softwares are uploaded by the developers themselves and Coolapk is one standard way to download apps in China.
> 
> Thanks again for your issue:)

Thanks for replying so fast, I'm glad you were able to clear things up about coolAPK!

**Comment by misaka-13766** [comment]
And I should notice one that the label of my app repository is different from nyas1's, just check them and you will find the difference :)

**Comment by TeaEndsAcronyms** [comment]
Yeah, I could tell :)
